### PR TITLE
Update to 1.20/1.20.1

### PR DESCRIPTION
**Pull request by KadTheHunter**
Only change it needed was deletion of `getMaterial()`, and changing `areNbtEqual()` to `canCombine()`.

Mod version bumped to 1.2, etc. etc.

My IDE also seems to have removed extra spaces, sorry about that :|

### CODE REVIEW

**Comment by Shauryat1** [comment]
@KadTheHunter  can u release the build on your device
I am trying to build with the gradle.bat/build.bat file but I am unable to find the built jar.

**Comment by KadTheHunter** [comment]
@Shauryat1 Oops mb, forgot to make a release on my fork, sorry!
It's out now, [Meteor Litematica Printer 1.2](https://github.com/KadTheHunter/meteor-litematica-printer/releases/tag/1.2)
.jar is downloadable there.

For your own build, check in `/build/libs/`; That's where gradle should put it.

**Comment by Shauryat1** [comment]
for some reason when i run "gradlew" in unzipped directory, it says the build was complete, but i am unable to find libs folder in build, just loom-cache

**Comment by Shauryat1** [comment]
I am using jdk 17 , and trying to build on my pc, even gradle.bat not working

**Comment by KadTheHunter** [comment]
@Shauryat1 
>when i run "gradlew"

Maybe it's because I'm still very new to Java development, but I've encountered issues running gradlew from the command-line as well.

My build was made using IntelliJ IDEA Community Edition, which just has a nice Gradle tab where I chose "build" and it handles it.

Just tested command-line myself, try `gradlew build`. Seems kind of obvious, but maybe you left `build` off?

**Pull request merged**
